
# Build stage
FROM rust:latest 

# Install Node.js and npm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

RUN . ~/.bashrc && nvm install 24

# Install Trunk
RUN cargo install trunk

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

RUN rustup target add wasm32-unknown-unknown

# Build the frontend
RUN trunk build --release

# Expose port 80
EXPOSE 80

# Start nginx
ENTRYPOINT ["trunk", "serve"]


