
# Build stage
FROM rust:latest 

# 安装 Node.js 和 npm（使用 Debian 包管理器）
RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nodejs

# Install Trunk
RUN cargo install trunk --locked

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

RUN rustup target add wasm32-unknown-unknown

# Build the frontend
RUN trunk build --release

# Expose port 80
EXPOSE 80

# Start nginx
ENTRYPOINT ["trunk", "serve"]


